### ISSUE TITLE
Records.Create() throws away return value

### ISSUE THREAD

**Issue by mitchellh** [crackcomm/cloudflare#5]
Records.Create() simply drops the resulting body of the API call. Most importantly, this drops the "id" meaning that any created record can't be safely looked back up. DNS can have multiple identical records with the same type and even value so there is no safe way to look that value up without getting this ID.

**Comment by crackcomm** [comment]
It now moves the created record ID [etc.](https://github.com/crackcomm/cloudflare/blob/dc358193164414054010e3fafdb6cc8def4eb864/client_records.go#L39) to record struct from argument, so we don't have to break the API. @mitchellh  What do You think?

**Comment by crackcomm** [comment]
Eventually we could break the API or unmarshal to struct from argument.

**Comment by mitchellh** [comment]
That seems fine to me!
