### ISSUE TITLE
Records.Details() gives "cannot unmarshal" error

### ISSUE THREAD

**Issue by mitchellh** [crackcomm/cloudflare#6]
Records.Details() gives an error about not being able to unmarshal into the proper resulting value. I've traced this down to the wrong type being sent to `json.Unmarshal`.

**Comment by crackcomm** [comment]
@mitchellh thanks, I tested it and I couldn't get this error, could You please validate that using command:

``` sh
$ cf records details --domain <domain> <record-id>
```

I also added validation for response status code (200, 201) and empty body.

**Comment by crackcomm** [comment]
Status code checking is actually unnecessary because CloudFlare gives us a list of errors in response.

**Comment by mitchellh** [comment]
No worries, let's just let it go. I don't need that API anymore so its okay.
